version: "3"

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    # For DHCP it is recommended to remove these ports and instead add: network_mode: "host"
    ports:
      - "192.168.1.7:53:53/tcp"
      - "192.168.1.7:53:53/udp"
      - "192.168.1.7:67:67/udp" # Only required if you are using Pi-hole as your DHCP server
      - "192.168.1.7:80:80/tcp"
    environment:
      TZ: 'America/Bogota'
      WEBPASSWORD: 'gunsrosados.1X'
    # Volumes store your data between container upgrades
    volumes:
      - './env/pihole/etc-pihole:/etc/pihole'
      - './env/pihole/etc-dnsmasq.d:/etc/dnsmasq.d'
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN # Required if you are using Pi-hole as your DHCP server, else not needed
    restart: unless-stopped
