services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - '${STATIC_IP}:53:53/udp'
      - '${STATIC_IP}:67:67/udp'
      - '${STATIC_IP}:80:80/tcp'
    environment:
      TZ: 'America/Bogota'
      WEBPASSWORD: $PIHOLE_PASS
    volumes:
      - './env/pihole/etc-pihole:/etc/pihole'
      - './env/pihole/etc-dnsmasq.d:/etc/dnsmasq.d'
    cap_add:
      - NET_ADMIN 
    restart: unless-stopped
  samba:
    container_name: samba
    image: dperson/samba
    restart: always
    command: '-u "${SAMBA_USER};${SAMBA_PASS}" -s "public;/public;yes;no"'
    stdin_open: true
    tty: true
    ports:
      - 139:130
      - 445:445
    volumes:
      - ./shared/public:/public
